apiVersion: client.apps.kubeflow.org/v1alpha1
kind: Client
metadata:
  creationTimestamp: null
  name: jlewi-kf-0316
  namespace: kubeflow
spec:
  appdir: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-kf-0316
  basicAuthPassword: $2a$10$bS26PV8OIdgyJfS/SuMcMOlOGPec7AbkRn0OHbcjsf2Lc6A9KBPby
  basicAuthUsername: jlewi
  componentParams:
    ambassador:
    - name: ambassadorServiceType
      value: NodePort
    application:
    - name: components
      value: <list-of-components>
    basic-auth-ingress:
    - initRequired: true
      name: ipName
      value: jlewi-kf-0316-ip
    - initRequired: true
      name: hostname
      value: jlewi-kf-0316.endpoints.kubeflow-ci-deployment.cloud.goog
    cert-manager:
    - initRequired: true
      name: acmeEmail
      value: jlewi@google.com
    cloud-endpoints:
    - name: secretName
      value: admin-gcp-sa
    jupyter:
    - name: platform
      value: gke
    pipeline:
    - name: mysqlPd
      value: jlewi-kf-0316-storage-metadata-store
    - name: minioPd
      value: jlewi-kf-0316-storage-artifact-store
  components:
  - ambassador
  - application
  - argo
  - basic-auth
  - basic-auth-ingress
  - centraldashboard
  - cert-manager
  - cloud-endpoints
  - jupyter
  - jupyter-web-app
  - katib
  - metacontroller
  - notebook-controller
  - pipeline
  - profiles
  - pytorch-operator
  - tensorboard
  - tf-job-operator
  email: jlewi@google.com
  hostname: jlewi-kf-0316.endpoints.kubeflow-ci-deployment.cloud.goog
  ipName: jlewi-kf-0316-ip
  packages:
  - argo
  - application
  - common
  - examples
  - gcp
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pipeline
  - profiles
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  platform: gcp
  project: kubeflow-ci-deployment
  repo: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-kf-0316/.cache/master/kubeflow
  skipInitProject: true
  useBasicAuth: true
  version: master
  zone: us-east1-d
status: {}
