kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  app.kubernetes.io/component: pipelines-ui
  app.kubernetes.io/instance: pipelines-ui-0.1.31
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: pipelines-ui
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: 0.1.31
resources:
- overlays/istio/virtual-service.yaml
- overlays/application/application.yaml
bases:
- base
configurations:
- overlays/istio/params.yaml
inventory:omitempty: null
