kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  app.kubernetes.io/component: pipeline-visualization-service
  app.kubernetes.io/instance: pipeline-visualization-service-0.1.31
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: pipeline-visualization-service
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: 0.1.31
resources:
- overlays/application/application.yaml
bases:
- base
inventory:omitempty: null
