kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  kustomize.component: iap-ingress
images:
- name: gcr.io/kubeflow-images-public/ingress-setup
  newName: gcr.io/jlewi-dev/kubeflow-images-public/ingress-setup
  newTag: latest
resources:
- job.yaml
- certificate.yaml
bases:
- ../../base
inventory:omitempty: null
