kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namePrefix: ml-pipeline-
commonLabels:
  app: ml-pipeline-persistenceagent
images:
- name: gcr.io/ml-pipeline/persistenceagent
  newName: gcr.io/jlewi-dev/ml-pipeline/persistenceagent
  newTag: 0.1.31
resources:
- clusterrole-binding.yaml
- clusterrole.yaml
- deployment.yaml
- service-account.yaml
inventory:omitempty: null
