kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: spartakus
images:
- name: gcr.io/google_containers/spartakus-amd64
  newName: gcr.io/jlewi-dev/google_containers/spartakus-amd64
  newTag: v1.1.0
vars:
- name: usageId
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: spartakus-parameters
  fieldref:
    fieldPath: data.usageId
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
configMapGenerator:
- name: spartakus-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
