kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namePrefix: application-controller-
namespace: kubeflow
images:
- name: gcr.io/kubeflow-images-public/kubernetes-sigs/application
  newName: gcr.io/jlewi-dev/kubeflow-images-public/kubernetes-sigs/application
  newTag: 1.0-beta
vars:
- name: project
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.project
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- service-account.yaml
- service.yaml
- stateful-set.yaml
configMapGenerator:
- name: parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
