kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  app.kubernetes.io/component: kubeflow
  app.kubernetes.io/instance: kubeflow-v0.7.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: kubeflow
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7.0
resources:
- overlays/application/application.yaml
bases:
- base
inventory:omitempty: null
