kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/instance: katib
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: katib
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7
resources:
- overlays/application/application.yaml
- overlays/istio/katib-ui-virtual-service.yaml
bases:
- base
configurations:
- overlays/istio/params.yaml
inventory:omitempty: null
