kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
commonLabels:
  kustomize.component: gpu-driver
images:
- name: gcr.io/google-containers/pause
  newName: gcr.io/jlewi-dev/google-containers/pause
  newTag: "2.0"
- name: cos-nvidia-installer
  newName: gcr.io/jlewi-dev/cos-nvidia-installer
  newTag: fixed
resources:
- daemon-set.yaml
inventory:omitempty: null
