kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
- deployment.yaml
bases:
- ../../base
configMapGenerator:
- name: parameters
  behavior: merge
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
inventory:omitempty: null
