kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: mysql
images:
- name: mysql
  newName: gcr.io/jlewi-dev/mysql
  newTag: "5.6"
vars:
- name: mysqlPvcName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-mysql-parameters
  fieldref:
    fieldPath: data.mysqlPvcName
resources:
- deployment.yaml
- service.yaml
- persistent-volume-claim.yaml
configMapGenerator:
- name: pipeline-mysql-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
