kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namePrefix: admission-webhook-
namespace: kubeflow
commonLabels:
  app: admission-webhook
  kustomize.component: admission-webhook
images:
- name: gcr.io/kubeflow-images-public/admission-webhook
  newName: gcr.io/jlewi-dev/kubeflow-images-public/admission-webhook
  newTag: v20190520-v0-139-gcee39dbc-dirty-0d8f4c
vars:
- name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: admission-webhook-parameters
  fieldref:
    fieldPath: data.namespace
- name: serviceName
  objref:
    apiVersion: v1
    kind: Service
    name: service
  fieldref:
    fieldPath: metadata.name
- name: deploymentName
  objref:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment
  fieldref:
    fieldPath: metadata.name
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- mutating-webhook-configuration.yaml
- service-account.yaml
- service.yaml
- crd.yaml
configMapGenerator:
- name: admission-webhook-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
