kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: minio
images:
- name: minio/minio
  newName: gcr.io/jlewi-dev/minio/minio
  newTag: RELEASE.2018-02-09T22-40-05Z
vars:
- name: minioPvcName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-minio-parameters
  fieldref:
    fieldPath: data.minioPvcName
resources:
- deployment.yaml
- secret.yaml
- service.yaml
- persistent-volume-claim.yaml
configMapGenerator:
- name: pipeline-minio-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
