kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: katib
  app.kubernetes.io/instance: katib
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: katib
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7
resources:
- application.yaml
bases:
- ../../base
inventory:omitempty: null
