apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  kustomize.component: iap-ingress
kind: Kustomization
namespace: istio-system
patchesStrategicMerge:
- overlays/gcp-credentials/deployment.yaml
- overlays/gcp-credentials/stateful-set.yaml
resources:
- overlays/managed-cert/cert.yaml
