kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
vars:
- name: user
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: default-install-parameters
  fieldref:
    fieldPath: data.user
- name: profile-name
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: default-install-parameters
  fieldref:
    fieldPath: data.profile-name
resources:
- profile-instance.yaml
configMapGenerator:
- name: default-install-parameters
  env: params.env
configurations:
- params.yaml
inventory:omitempty: null
