kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  kustomize.component: iap-ingress
resources:
- cert.yaml
bases:
- ../../base
inventory:omitempty: null
