kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  kustomize.component: tensorboard
images:
- name: tensorflow/tensorflow
  newName: gcr.io/jlewi-dev/tensorflow/tensorflow
  newTag: 1.8.0
vars:
- name: namespace
  objref:
    apiVersion: v1
    kind: Service
    name: tensorboard
  fieldref:
    fieldPath: metadata.namespace
- name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.clusterDomain
resources:
- deployment.yaml
- service.yaml
configMapGenerator:
- name: parameters
  env: params.env
configurations:
- params.yaml
inventory:omitempty: null
