kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namePrefix: notebook-controller-
namespace: kubeflow
commonLabels:
  app: notebook-controller
  kustomize.component: notebook-controller
images:
- name: gcr.io/kubeflow-images-public/notebook-controller
  newName: gcr.io/jlewi-dev/kubeflow-images-public/notebook-controller
  digest: sha256:6490f737000bd1d2520ac4b8cbde2b09749cdb291b1967ddda95d05131db49db
vars:
- name: POD_LABELS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.POD_LABELS
- name: USE_ISTIO
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.USE_ISTIO
- name: ISTIO_GATEWAY
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.ISTIO_GATEWAY
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
configMapGenerator:
- name: parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
inventory:omitempty: null
