kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
images:
- name: gcr.io/ml-pipeline/frontend
  newName: gcr.io/jlewi-dev/ml-pipeline/frontend
  newTag: 0.1.31
vars:
- name: ui-namespace
  objref:
    apiVersion: v1
    kind: Service
    name: ml-pipeline-ui
  fieldref:
    fieldPath: metadata.namespace
- name: ui-clusterDomain
  objref:
    version: v1
    kind: ConfigMap
    name: ui-parameters
  fieldref:
    fieldPath: data.uiClusterDomain
- name: service
  objref:
    apiVersion: v1
    kind: Service
    name: ml-pipeline-ui
  fieldref:
    fieldPath: metadata.name
- name: tensorboard-service
  objref:
    apiVersion: v1
    kind: Service
    name: ml-pipeline-tensorboard-ui
  fieldref:
    fieldPath: metadata.name
resources:
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
- service.yaml
configMapGenerator:
- name: ui-parameters
  env: params.env
configurations:
- params.yaml
inventory:omitempty: null
