kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: ml-pipeline
images:
- name: gcr.io/ml-pipeline/api-server
  newName: gcr.io/jlewi-dev/ml-pipeline/api-server
  newTag: 0.1.31
resources:
- config-map.yaml
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
- service.yaml
inventory:omitempty: null
