namespace: kubeflow
images:
- name: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-controller
  newName: gcr.io/jlewi-dev/kubeflow-images-public/katib/v1alpha3/katib-controller
  newTag: 7ade03b
- name: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-manager
  newName: gcr.io/jlewi-dev/kubeflow-images-public/katib/v1alpha3/katib-manager
  newTag: 7ade03b
- name: gcr.io/kubeflow-images-public/katib/v1alpha3/katib-ui
  newName: gcr.io/jlewi-dev/kubeflow-images-public/katib/v1alpha3/katib-ui
  newTag: 7ade03b
- name: mysql
  newName: gcr.io/jlewi-dev/mysql
  newTag: "8"
vars:
- name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: katib-parameters
  fieldref:
    fieldPath: data.clusterDomain
- name: namespace
  objref:
    apiVersion: v1
    kind: Service
    name: katib-ui
  fieldref:
    fieldPath: metadata.namespace
resources:
- katib-configmap.yaml
- katib-controller-deployment.yaml
- katib-controller-rbac.yaml
- katib-controller-secret.yaml
- katib-controller-service.yaml
- katib-db-deployment.yaml
- katib-db-pvc.yaml
- katib-db-secret.yaml
- katib-db-service.yaml
- katib-manager-deployment.yaml
- katib-manager-service.yaml
- katib-ui-deployment.yaml
- katib-ui-rbac.yaml
- katib-ui-service.yaml
- trial-template-configmap.yaml
configMapGenerator:
- name: katib-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
