apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
commonLabels:
  app.kubernetes.io/component: tfjob
  app.kubernetes.io/instance: $(generateName)
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: tf-job-operator
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
configMapGenerator:
- behavior: unspecified
  env: overlays/application/params.env
  name: tf-job-operator-parameters
configurations:
- overlays/istio/params.yaml
- overlays/application/params.yaml
kind: Kustomization
namespace: kubeflow
resources:
- overlays/istio/virtual-service.yaml
- overlays/application/application.yaml
vars:
- fieldref:
    fieldPath: data.generateName
  name: generateName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: tf-job-operator-parameters
