kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
vars:
- name: clusterRbacConfig
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: istio-parameters
  fieldref:
    fieldPath: data.clusterRbacConfig
- name: gatewaySelector
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: istio-parameters
  fieldref:
    fieldPath: data.gatewaySelector
resources:
- kf-istio-resources.yaml
- cluster-roles.yaml
configMapGenerator:
- name: istio-parameters
  env: params.env
configurations:
- params.yaml
inventory:omitempty: null
