kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
images:
- name: docker.io/istio/kubectl
  newName: gcr.io/jlewi-dev/istio/kubectl
  newTag: 1.1.6
- name: docker.io/istio/galley
  newName: gcr.io/jlewi-dev/istio/galley
  newTag: 1.1.6
- name: docker.io/istio/proxyv2
  newName: gcr.io/jlewi-dev/istio/proxyv2
  newTag: 1.1.6
- name: grafana/grafana
  newName: gcr.io/jlewi-dev/grafana/grafana
  newTag: 6.0.2
- name: docker.io/kiali/kiali
  newName: gcr.io/jlewi-dev/kiali/kiali
  newTag: v0.16
- name: docker.io/istio/mixer
  newName: gcr.io/jlewi-dev/istio/mixer
  newTag: 1.1.6
- name: docker.io/istio/pilot
  newName: gcr.io/jlewi-dev/istio/pilot
  newTag: 1.1.6
- name: docker.io/prom/prometheus
  newName: gcr.io/jlewi-dev/prom/prometheus
  newTag: v2.3.1
- name: docker.io/istio/citadel
  newName: gcr.io/jlewi-dev/istio/citadel
  newTag: 1.1.6
- name: docker.io/istio/sidecar_injector
  newName: gcr.io/jlewi-dev/istio/sidecar_injector
  newTag: 1.1.6
- name: docker.io/jaegertracing/all-in-one
  newName: gcr.io/jlewi-dev/jaegertracing/all-in-one
  newTag: "1.9"
resources:
- istio-noauth.yaml
inventory:omitempty: null
