apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: jlewi-0323-iap
  namespace: kubeflow
spec:
  appdir: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-0323-iap
  componentParams:
    application:
    - name: components
      value: '["ambassador" ,"argo" ,"centraldashboard" ,"cert-manager" ,"cloud-endpoints"
        ,"gpu-driver" ,"iap-ingress" ,"jupyter" ,"jupyter-web-app" ,"katib" ,"notebook-controller"
        ,"pipeline" ,"profiles" ,"pytorch-operator" ,"tensorboard" ,"tf-job-operator"]'
    cert-manager:
    - initRequired: true
      name: acmeEmail
      value: jlewi@google.com
    cloud-endpoints:
    - name: secretName
      value: admin-gcp-sa
    iap-ingress:
    - initRequired: true
      name: ipName
      value: jlewi-0323-iap-ip
    - initRequired: true
      name: hostname
      value: jlewi-0323-iap.endpoints.cloud-ml-dev.cloud.goog
    jupyter:
    - name: jupyterHubAuthenticator
      value: iap
    - name: platform
      value: gke
    pipeline:
    - name: mysqlPd
      value: jlewi-0323-iap-storage-metadata-store
    - name: minioPd
      value: jlewi-0323-iap-storage-artifact-store
  components:
  - ambassador
  - application
  - argo
  - centraldashboard
  - cert-manager
  - cloud-endpoints
  - gpu-driver
  - iap-ingress
  - jupyter
  - jupyter-web-app
  - katib
  - metacontroller
  - notebook-controller
  - pipeline
  - profiles
  - pytorch-operator
  - tensorboard
  - tf-job-operator
  deleteStorage: false
  email: jlewi@google.com
  hostname: jlewi-0323-iap.endpoints.cloud-ml-dev.cloud.goog
  ipName: jlewi-0323-iap-ip
  packages:
  - application
  - argo
  - common
  - examples
  - gcp
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pipeline
  - profiles
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  platform: gcp
  project: cloud-ml-dev
  repo: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-0323-iap/.cache/master/kubeflow
  serverVersion: file:/home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-0323-iap/.cache/master/releasing/releaser/lib/v1.9.7/swagger.json
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
  zone: us-east1-d
status: {}
