kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namePrefix: ml-pipeline-
commonLabels:
  app: ml-pipeline-visualizationserver
images:
- name: gcr.io/ml-pipeline/visualization-server
  newName: gcr.io/jlewi-dev/ml-pipeline/visualization-server
  newTag: 0.1.27
resources:
- deployment.yaml
- service.yaml
inventory:omitempty: null
