kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
resources:
- overlays/istio/virtual-service.yaml
- overlays/istio/virtual-service-metadata-grpc.yaml
bases:
- base
configurations:
- overlays/istio/params.yaml
inventory:omitempty: null
