kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
- persistent-volume-claim.yaml
vars:
- name: minioPd
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-minio-parameters
  fieldref:
    fieldPath: data.minioPd
- name: minioPvName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-minio-parameters
  fieldref:
    fieldPath: data.minioPvName
resources:
- persistent-volume.yaml
bases:
- ../../base
configMapGenerator:
- name: pipeline-minio-parameters
  behavior: merge
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
