apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: jlewi-0402-basic
  namespace: kubeflow
spec:
  appdir: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-0402-basic
  componentParams:
    cert-manager:
    - initRequired: true
      name: acmeEmail
      value: johnDoe@acme.com
    cloud-endpoints:
    - name: secretName
      value: admin-gcp-sa
    iap-ingress:
    - initRequired: true
      name: ipName
      value: ipName
    - initRequired: true
      name: hostname
      value: <deployName>.endpoints.<project>.cloud.goog
    pipeline:
    - name: mysqlPd
      value: <deployName>-storage-metadata-store
    - name: minioPd
      value: <deployName>-storage-artifact-store
    spartakus:
    - initRequired: true
      name: usageId
      value: <randomly-generated-id>
    - initRequired: true
      name: reportUsage
      value: "true"
  components:
  - ambassador
  - argo
  - centraldashboard
  - cert-manager
  - cloud-endpoints
  - gcp-credentials-admission-webhook
  - gpu-driver
  - iap-ingress
  - jupyter-web-app
  - katib
  - metacontroller
  - notebook-controller
  - pipeline
  - pytorch-operator
  - spartakus
  - tensorboard
  - tf-job-operator
  email: jlewi@google.com
  packages:
  - argo
  - common
  - examples
  - gcp
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pipeline
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  platform: gcp
  project: kubeflow-ci-dpeloyment
  repo: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-0402-basic/.cache/master/kubeflow
  serverVersion: file:/home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-0402-basic/.cache/master/bootstrap/k8sSpec/v1.11.7/api/openapi-spec/swagger.json
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
status: {}
