kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  kustomize.component: iap-ingress
images:
- name: gcr.io/kubeflow-images-public/envoy
  newName: gcr.io/jlewi-dev/kubeflow-images-public/envoy
  newTag: v20180309-0fb4886b463698702b6a08955045731903a18738
- name: gcr.io/kubeflow-images-public/ingress-setup
  newName: gcr.io/jlewi-dev/kubeflow-images-public/ingress-setup
  newTag: latest
- name: gcr.io/cloud-solutions-group/esp-sample-app
  newName: gcr.io/jlewi-dev/cloud-solutions-group/esp-sample-app
  newTag: 1.0.0
vars:
- name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.namespace
- name: appName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.appName
- name: hostname
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.hostname
- name: ipName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.ipName
- name: ingressName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.ingressName
- name: issuer
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.issuer
- name: oauthSecretName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.oauthSecretName
- name: project
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.project
- name: adminSaSecretName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.adminSaSecretName
- name: tlsSecretName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.tlsSecretName
- name: istioNamespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.istioNamespace
resources:
- backend-config.yaml
- cloud-endpoint.yaml
- cluster-role-binding.yaml
- cluster-role.yaml
- config-map.yaml
- deployment.yaml
- ingress.yaml
- policy.yaml
- service-account.yaml
- service.yaml
- stateful-set.yaml
configMapGenerator:
- name: parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
