apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: jlewi-devlab4
  namespace: kubeflow
spec:
  appdir: /home/jlewi/git_jlewi-kubeflow-dev/kubeflow-deployments/jlewi-devlab4
  componentParams:
    application:
    - name: overlay
      value: application
    argo:
    - name: overlay
      value: istio
    basic-auth-ingress:
    - name: namespace
      value: istio-system
    bootstrap:
    - name: webhookNamePrefix
      value: admission-webhook-
    centraldashboard:
    - name: overlay
      value: istio
    - name: overlay
      value: application
    cert-manager:
    - initRequired: true
      name: acmeEmail
      value: johnDoe@acme.com
    cloud-endpoints:
    - name: secretName
      value: admin-gcp-sa
    iap-ingress:
    - name: namespace
      value: istio-system
    - initRequired: true
      name: ipName
      value: ipName
    - initRequired: true
      name: hostname
      value: <deployName>.endpoints.<project>.cloud.goog
    istio:
    - name: clusterRbacConfig
      value: "ON"
    istio-crds:
    - name: namespace
      value: istio-system
    istio-install:
    - name: namespace
      value: istio-system
    jupyter-web-app:
    - name: overlay
      value: istio
    - name: overlay
      value: application
    katib-ui:
    - name: overlay
      value: istio
    metadata:
    - name: overlay
      value: istio
    minio:
    - name: overlay
      value: minioPd
    - name: minioPd
      value: dls-kf-storage-artifact-store
    - name: minioPvName
      value: minio-pv
    - name: minioPvcName
      value: minio-pv-claim
    mysql:
    - name: overlay
      value: mysqlPd
    - name: mysqlPd
      value: dls-kf-storage-metadata-store
    - name: mysqlPvName
      value: mysql-pv
    - name: mysqlPvcName
      value: mysql-pv-claim
    notebook-controller:
    - name: overlay
      value: istio
    - name: injectGcpCredentials
      value: "true"
    - name: overlay
      value: application
    pipeline:
    - name: mysqlPd
      value: dls-kf-storage-metadata-store
    - name: minioPd
      value: dls-kf-storage-artifact-store
    pipelines-ui:
    - name: overlay
      value: istio
    profiles:
    - name: overlay
      value: istio
    - initRequired: true
      name: admin
      value: johnDoe@acme.com
    pytorch-operator:
    - name: overlay
      value: application
    spartakus:
    - initRequired: true
      name: usageId
      value: <randomly-generated-id>
    - initRequired: true
      name: reportUsage
      value: "true"
    tensorboard:
    - name: overlay
      value: istio
    tf-job-operator:
    - name: overlay
      value: istio
    - name: overlay
      value: application
  components:
  - istio-crds
  - istio-install
  - istio
  - application-crds
  - application
  - metacontroller
  - argo
  - centraldashboard
  - webhook
  - bootstrap
  - jupyter-web-app
  - katib-db
  - katib-manager
  - katib-controller
  - katib-ui
  - metrics-collector
  - metadata
  - suggestion
  - notebook-controller
  - pytorch-job-crds
  - pytorch-operator
  - spartakus
  - tensorboard
  - tf-job-operator
  - api-service
  - minio
  - mysql
  - persistent-agent
  - pipelines-runner
  - pipelines-ui
  - pipelines-viewer
  - scheduledworkflow
  - cert-manager-crds
  - cert-manager
  - cloud-endpoints
  - profiles
  - gpu-driver
  - iap-ingress
  enableApplications: true
  manifestsRepo: /home/jlewi/git_jlewi-kubeflow-dev/kubeflow-deployments/jlewi-devlab4/.cache/manifests/manifests-0.6.2
  packageManager: kustomize
  packages:
  - argo
  - common
  - examples
  - admission-webhook
  - jupyter
  - katib-v1alpha2
  - metacontroller
  - metadata
  - modeldb
  - mpi-job
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  - pipeline
  - istio
  - cert-manager
  - gcp
  - profiles
  - application
  platform: gcp
  project: kubeflow-contrib19-sjc-8086
  repo: /home/jlewi/git_jlewi-kubeflow-dev/kubeflow-deployments/jlewi-devlab4/.cache/kubeflow/v0.6.2/kubeflow
  repos:
  - name: kubeflow
    uri: https://github.com/kubeflow/kubeflow/tarball/v0.6.2?archive=tar.gz
  - name: manifests
    root: manifests-v0.6.2
    uri: https://github.com/kubeflow/manifests/archive/v0.6.2.tar.gz
  serverVersion: file:/home/jlewi/git_jlewi-kubeflow-dev/kubeflow-deployments/jlewi-devlab4/.cache/kubeflow/v0.6.2/bootstrap/k8sSpec/v1.11.7/api/openapi-spec/swagger.json
  useBasicAuth: false
  useIstio: true
  version: v0.6.2
status:
  reposCache:
    kubeflow:
      localPath: '"/home/jlewi/git_jlewi-kubeflow-dev/kubeflow-deployments/jlewi-devlab4/.cache/kubeflow/kubeflow-kubeflow-47a0e4c"'
    manifests:
      localPath: '"/home/jlewi/git_jlewi-kubeflow-dev/kubeflow-deployments/jlewi-devlab4/.cache/manifests/manifests-0.6.2"'
