kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: knative-serving
commonLabels:
  app.kubernetes.io/component: knative-serving-install
  app.kubernetes.io/instance: knative-serving-install-v0.8.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: knative-serving-install
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.8.0
resources:
- overlays/application/application.yaml
bases:
- base
inventory:omitempty: null
