kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
- persistent-volume-claim.yaml
vars:
- name: mysqlPd
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-mysql-parameters
  fieldref:
    fieldPath: data.mysqlPd
- name: mysqlPvName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: pipeline-mysql-parameters
  fieldref:
    fieldPath: data.mysqlPvName
resources:
- persistent-volume.yaml
bases:
- ../../base
configMapGenerator:
- name: pipeline-mysql-parameters
  behavior: merge
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
