kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namePrefix: jupyter-web-app-
namespace: kubeflow
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
images:
- name: gcr.io/kubeflow-images-public/jupyter-web-app
  newName: gcr.io/jlewi-dev/kubeflow-images-public/jupyter-web-app
  newTag: 9419d4d
vars:
- name: policy
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.policy
- name: prefix
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.prefix
- name: clusterDomain
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.clusterDomain
- name: namespace
  objref:
    apiVersion: v1
    kind: Service
    name: service
  fieldref:
    fieldPath: metadata.namespace
- name: userid-header
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.userid-header
- name: userid-prefix
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.userid-prefix
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- config-map.yaml
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
- service.yaml
configMapGenerator:
- name: parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
