kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
- deployment.yaml
images:
- name: gcr.io/$(project)/profile-controller
  newName: gcr.io/jlewi-dev
  newTag: latest
vars:
- name: project
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: parameters
  fieldref:
    fieldPath: data.project
bases:
- ../../base
configMapGenerator:
- name: parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
