kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: cloud-endpoints-controller
  kustomize.component: cloud-endpoints
images:
- name: gcr.io/cloud-solutions-group/cloud-endpoints-controller
  newName: gcr.io/jlewi-dev/cloud-solutions-group/cloud-endpoints-controller
  newTag: 0.2.1
vars:
- name: secretName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cloud-endpoints-parameters
  fieldref:
    fieldPath: data.secretName
- name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: cloud-endpoints-parameters
  fieldref:
    fieldPath: data.namespace
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- composite-controller.yaml
- crd.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
configMapGenerator:
- name: cloud-endpoints-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
configurations:
- params.yaml
inventory:omitempty: null
