kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
patchesStrategicMerge:
- stateful-set.yaml
images:
- name: gcr.io/$(project)/application-controller
  newName: gcr.io/jlewi-dev
  newTag: latest
bases:
- ../../base
inventory:omitempty: null
