kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  kustomize.component: kfserving
images:
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: gcr.io/jlewi-dev/kubebuilder/kube-rbac-proxy
  newTag: v0.4.0
- name: $(registry)/kfserving-controller
  newName: gcr.io/jlewi-dev
  newTag: 0.2.0
vars:
- name: registry
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: kfserving-parameters
  fieldref:
    fieldPath: data.registry
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- config-map.yaml
- secret.yaml
- statefulset.yaml
- service.yaml
configMapGenerator:
- name: kfserving-parameters
  env: params.env
configurations:
- params.yaml
inventory:omitempty: null
