kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  app: ml-pipeline-scheduledworkflow
images:
- name: gcr.io/ml-pipeline/scheduledworkflow
  newName: gcr.io/jlewi-dev/ml-pipeline/scheduledworkflow
  newTag: 0.1.31
resources:
- cluster-role.yaml
- crd.yaml
- deployment.yaml
- role-binding.yaml
- role.yaml
- service-account.yaml
inventory:omitempty: null
