apiVersion: kfdef.apps.kubeflow.org/v1alpha1
kind: KfDef
metadata:
  creationTimestamp: null
  name: jlewi-0424-vpc
  namespace: kubeflow
spec:
  appdir: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-0424-vpc
  componentParams:
    argo:
    - initRequired: true
      name: injectIstio
      value: "false"
    centraldashboard:
    - initRequired: true
      name: injectIstio
      value: "false"
    cert-manager:
    - initRequired: true
      name: acmeEmail
      value: jlewi@google.com
    cloud-endpoints:
    - name: secretName
      value: admin-gcp-sa
    iap-ingress:
    - initRequired: true
      name: ipName
      value: jlewi-0424-vpc-ip
    - initRequired: true
      name: hostname
      value: jlewi-0424-vpc.endpoints.kubeflow-dev.cloud.goog
    jupyter-web-app:
    - initRequired: true
      name: injectIstio
      value: "false"
    katib:
    - initRequired: true
      name: injectIstio
      value: "false"
    notebook-controller:
    - name: injectGcpCredentials
      value: "true"
    pipeline:
    - name: mysqlPd
      value: jlewi-0424-vpc-storage-metadata-store
    - name: minioPd
      value: jlewi-0424-vpc-storage-artifact-store
    - name: injectIstio
      value: "false"
    spartakus:
    - initRequired: true
      name: usageId
      value: "3980853699355027758"
    - initRequired: true
      name: reportUsage
      value: "true"
    tensorboard:
    - initRequired: true
      name: injectIstio
      value: "false"
    tf-job-operator:
    - initRequired: true
      name: injectIstio
      value: "false"
  components:
  - metacontroller
  - ambassador
  - argo
  - centraldashboard
  - cert-manager
  - cloud-endpoints
  - gcp-credentials-admission-webhook
  - gpu-driver
  - iap-ingress
  - jupyter-web-app
  - katib
  - notebook-controller
  - pipeline
  - pytorch-operator
  - spartakus
  - tensorboard
  - tf-job-operator
  email: jlewi@google.com
  hostname: jlewi-0424-vpc.endpoints.kubeflow-dev.cloud.goog
  ipName: jlewi-0424-vpc-ip
  packages:
  - argo
  - common
  - examples
  - gcp
  - jupyter
  - katib
  - metacontroller
  - modeldb
  - mpi-job
  - pipeline
  - pytorch-job
  - seldon
  - tensorboard
  - tf-serving
  - tf-training
  platform: gcp
  project: kubeflow-dev
  repo: /home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-0424-vpc/.cache/master/kubeflow
  serverVersion: file:/home/jlewi/git_kubeflow-dev/kubeflow-deployments/jlewi-0424-vpc/.cache/master/bootstrap/k8sSpec/v1.11.7/api/openapi-spec/swagger.json
  skipInitProject: true
  useBasicAuth: false
  useIstio: false
  version: master
  zone: us-east1-d
status: {}
