kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app.kubernetes.io/component: mysql
  app.kubernetes.io/instance: mysql-0.1.31
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: mysql
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: 0.1.31
resources:
- application.yaml
bases:
- ../../base
inventory:omitempty: null
