kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  app.kubernetes.io/component: profiles
  app.kubernetes.io/instance: profiles-v0.7.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: profiles
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.7.0
resources:
- overlays/application/application.yaml
- overlays/istio/virtual-service.yaml
bases:
- base
configurations:
- overlays/istio/params.yaml
inventory:omitempty: null
