apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- base
- overlays/istio
commonLabels:
  app.kubernetes.io/component: jupyter
  app.kubernetes.io/instance: $(generateName)
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/name: jupyter-web-app
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v0.6
configMapGenerator:
- behavior: unspecified
  env: overlays/application/params.env
  name: jupyter-web-app-parameters
configurations:
- overlays/application/params.yaml
kind: Kustomization
namespace: kubeflow
resources:
- overlays/application/application.yaml
vars:
- fieldref:
    fieldPath: data.generateName
  name: generateName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: jupyter-web-app-parameters
