kind: Kustomization
apiversion: kustomize.config.k8s.io/v1beta1
namespace: kubeflow
commonLabels:
  app: pipeline-runner
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- service-account.yaml
inventory:omitempty: null
